demons =
{
   "Aello":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Aeros":{
      "trifusion":"false",
      "level":"11",
      "cutoff":"200"
   },
   "Alice":{
      "trifusion":"true",
      "level":"35",
      "cutoff":"200"
   },
   "Alp":{
      "trifusion":"false",
      "level":"8",
      "cutoff":"15"
   },
   "Ameno-Uzume":{
      "trifusion":"false",
      "level":"24",
      "cutoff":"47"
   },
   "Andras":{
      "trifusion":"false",
      "level":"15",
      "cutoff":"29"
   },
   "Angel":{
      "trifusion":"false",
      "level":"11",
      "cutoff":"21"
   },
   "Apis":{
      "trifusion":"false",
      "level":"24",
      "cutoff":"47"
   },
   "Apsaras":{
      "trifusion":"false",
      "level":"8",
      "cutoff":"15"
   },
   "Aquans":{
      "trifusion":"false",
      "level":"15",
      "cutoff":"200"
   },
   "Arahabaki":{
      "trifusion":"false",
      "level":"83",
      "cutoff":"200"
   },
   "Archangel":{
      "trifusion":"false",
      "level":"17",
      "cutoff":"33"
   },
   "Artemis":{
      "trifusion":"false",
      "level":"30",
      "cutoff":"59"
   },
   "Azumi":{
      "trifusion":"false",
      "level":"10",
      "cutoff":"19"
   },
   "Badb Catha":{
      "trifusion":"false",
      "level":"54",
      "cutoff":"107"
   },
   "Bai Ze":{
      "trifusion":"false",
      "level":"27",
      "cutoff":"53"
   },
   "Baphomet":{
      "trifusion":"false",
      "level":"30",
      "cutoff":"59"
   },
   "Basilisk":{
      "trifusion":"false",
      "level":"43",
      "cutoff":"85"
   },
   "Beiji Weng":{
      "trifusion":"true",
      "level":"93",
      "cutoff":"200"
   },
   "Berith":{
      "trifusion":"false",
      "level":"58",
      "cutoff":"115"
   },
   "Bicorn":{
      "trifusion":"false",
      "level":"17",
      "cutoff":"33"
   },
   "Bishamonten":{
      "trifusion":"true",
      "level":"72",
      "cutoff":"200"
   },
   "Black Ooze":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Blob":{
      "trifusion":"false",
      "level":"16",
      "cutoff":"31"
   },
   "Bucca-Boo":{
      "trifusion":"false",
      "level":"24",
      "cutoff":"47"
   },
   "Cait Sith":{
      "trifusion":"false",
      "level":"7",
      "cutoff":"13"
   },
   "Camazotz":{
      "trifusion":"false",
      "level":"69",
      "cutoff":"138"
   },
   "Catoblepas":{
      "trifusion":"false",
      "level":"50",
      "cutoff":"99"
   },
   "Celaeno":{
      "trifusion":"false",
      "level":"30",
      "cutoff":"59"
   },
   "Cerberus":{
      "trifusion":"false",
      "level":"49",
      "cutoff":"200"
   },
   "Chatterskull":{
      "trifusion":"false",
      "level":"33",
      "cutoff":"65"
   },
   "Chernobog":{
      "trifusion":"false",
      "level":"62",
      "cutoff":"200"
   },
   "Choronzon":{
      "trifusion":"false",
      "level":"17",
      "cutoff":"33"
   },
   "Coatlicue":{
      "trifusion":"false",
      "level":"33",
      "cutoff":"65"
   },
   "Cockatrice":{
      "trifusion":"false",
      "level":"8",
      "cutoff":"15"
   },
   "Cu Chulainn":{
      "trifusion":"false",
      "level":"44",
      "cutoff":"87"
   },
   "Cu Sith":{
      "trifusion":"false",
      "level":"13",
      "cutoff":"25"
   },
   "Cyclops":{
      "trifusion":"false",
      "level":"46",
      "cutoff":"100"
   },
   "Dakini":{
      "trifusion":"false",
      "level":"65",
      "cutoff":"200"
   },
   "Datsue-Ba":{
      "trifusion":"false",
      "level":"9",
      "cutoff":"17"
   },
   "Dawon":{
      "trifusion":"false",
      "level":"42",
      "cutoff":"83"
   },
   "Decarabia":{
      "trifusion":"false",
      "level":"50",
      "cutoff":"99"
   },
   "Dionysus":{
      "trifusion":"true",
      "level":"58",
      "cutoff":"200"
   },
   "Dis":{
      "trifusion":"false",
      "level":"23",
      "cutoff":"45"
   },
   "Dominion":{
      "trifusion":"false",
      "level":"64",
      "cutoff":"127"
   },
   "Dwarf":{
      "trifusion":"false",
      "level":"30",
      "cutoff":"59"
   },
   "Elf":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Eligor":{
      "trifusion":"false",
      "level":"43",
      "cutoff":"85"
   },
   "Empusa":{
      "trifusion":"false",
      "level":"14",
      "cutoff":"27"
   },
   "Erthys":{
      "trifusion":"false",
      "level":"7",
      "cutoff":"200"
   },
   "Fenrir":{
      "trifusion":"false",
      "level":"57",
      "cutoff":"113"
   },
   "Flamies":{
      "trifusion":"false",
      "level":"20",
      "cutoff":"200"
   },
   "Fomorian":{
      "trifusion":"false",
      "level":"27",
      "cutoff":"53"
   },
   "Forneus":{
      "trifusion":"false",
      "level":"29",
      "cutoff":"57"
   },
   "Freya":{
      "trifusion":"false",
      "level":"38",
      "cutoff":"75"
   },
   "Furiae":{
      "trifusion":"false",
      "level":"45",
      "cutoff":"89"
   },
   "Fuu-Ki":{
      "trifusion":"false",
      "level":"72",
      "cutoff":"200"
   },
   "Gaki":{
      "trifusion":"false",
      "level":"7",
      "cutoff":"13"
   },
   "Gandharva":{
      "trifusion":"false",
      "level":"23",
      "cutoff":"45"
   },
   "Ganesha":{
      "trifusion":"false",
      "level":"58",
      "cutoff":"200"
   },
   "Ganga":{
      "trifusion":"false",
      "level":"39",
      "cutoff":"77"
   },
   "Garm":{
      "trifusion":"false",
      "level":"9",
      "cutoff":"17"
   },
   "Garuda":{
      "trifusion":"false",
      "level":"65",
      "cutoff":"200"
   },
   "Ghoul":{
      "trifusion":"false",
      "level":"11",
      "cutoff":"21"
   },
   "Girimehkala":{
      "trifusion":"false",
      "level":"70",
      "cutoff":"139"
   },
   "Gorgon":{
      "trifusion":"false",
      "level":"32",
      "cutoff":"63"
   },
   "Gyuki":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Hanuman":{
      "trifusion":"true",
      "level":"71",
      "cutoff":"200"
   },
   "Harpy":{
      "trifusion":"false",
      "level":"7",
      "cutoff":"13"
   },
   "Harthor":{
      "trifusion":"false",
      "level":"18",
      "cutoff":"35"
   },
   "Hayagriva":{
      "trifusion":"false",
      "level":"57",
      "cutoff":"113"
   },
   "Hecate":{
      "trifusion":"true",
      "level":"59",
      "cutoff":"200"
   },
   "Hecatonchires":{
      "trifusion":"true",
      "level":"82",
      "cutoff":"200"
   },
   "Hel":{
      "trifusion":"false",
      "level":"46",
      "cutoff":"91"
   },
   "Hell Biker":{
      "trifusion":"true",
      "level":"46",
      "cutoff":"200"
   },
   "High Pixie":{
      "trifusion":"false",
      "level":"15",
      "cutoff":"29"
   },
   "Houou":{
      "trifusion":"false",
      "level":"20",
      "cutoff":"39"
   },
   "Hraesvelgr":{
      "trifusion":"false",
      "level":"78",
      "cutoff":"200"
   },
   "Hua Po":{
      "trifusion":"false",
      "level":"5",
      "cutoff":"9"
   },
   "Incubus":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Inugami":{
      "trifusion":"false",
      "level":"18",
      "cutoff":"35"
   },
   "Isora":{
      "trifusion":"false",
      "level":"14",
      "cutoff":"27"
   },
   "Jack Frost":{
      "trifusion":"false",
      "level":"11",
      "cutoff":"21"
   },
   "Jatayu":{
      "trifusion":"false",
      "level":"28",
      "cutoff":"55"
   },
   "Jikokuten":{
      "trifusion":"false",
      "level":"52",
      "cutoff":"103"
   },
   "Jinn":{
      "trifusion":"false",
      "level":"44",
      "cutoff":"87"
   },
   "Kaichi":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Kaiwan":{
      "trifusion":"false",
      "level":"47",
      "cutoff":"93"
   },
   "Kali":{
      "trifusion":"false",
      "level":"68",
      "cutoff":"133"
   },
   "Karasu-Tengu":{
      "trifusion":"false",
      "level":"28",
      "cutoff":"55"
   },
   "Kelpie":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Kikuri-Hime":{
      "trifusion":"false",
      "level":"18",
      "cutoff":"35"
   },
   "Kin-Ki":{
      "trifusion":"false",
      "level":"66",
      "cutoff":"131"
   },
   "King Frost":{
      "trifusion":"true",
      "level":"40",
      "cutoff":"200"
   },
   "Kirin":{
      "trifusion":"false",
      "level":"41",
      "cutoff":"81"
   },
   "Knocker":{
      "trifusion":"false",
      "level":"11",
      "cutoff":"21"
   },
   "Kodama":{
      "trifusion":"false",
      "level":"3",
      "cutoff":"5"
   },
   "Koppa Tengu":{
      "trifusion":"false",
      "level":"15",
      "cutoff":"29"
   },
   "Koumokuten":{
      "trifusion":"false",
      "level":"45",
      "cutoff":"89"
   },
   "Kurama Tengu":{
      "trifusion":"false",
      "level":"48",
      "cutoff":"95"
   },
   "Kushinada-Hime":{
      "trifusion":"false",
      "level":"26",
      "cutoff":"51"
   },
   "Lamia":{
      "trifusion":"false",
      "level":"47",
      "cutoff":"93"
   },
   "Legion":{
      "trifusion":"false",
      "level":"38",
      "cutoff":"75"
   },
   "Lilim":{
      "trifusion":"false",
      "level":"20",
      "cutoff":"39"
   },
   "Lilith":{
      "trifusion":"true",
      "level":"92",
      "cutoff":"200"
   },
   "Loa":{
      "trifusion":"false",
      "level":"52",
      "cutoff":"103"
   },
   "Loki":{
      "trifusion":"true",
      "level":"69",
      "cutoff":"200"
   },
   "Macha":{
      "trifusion":"false",
      "level":"12",
      "cutoff":"23"
   },
   "Makami":{
      "trifusion":"false",
      "level":"22",
      "cutoff":"43"
   },
   "Mara":{
      "trifusion":"true",
      "level":"95",
      "cutoff":"200"
   },
   "Matador":{
      "trifusion":"true",
      "level":"30",
      "cutoff":"200"
   },
   "Mithra":{
      "trifusion":"true",
      "level":"74",
      "cutoff":"200"
   },
   "Mizuchi":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Moloch":{
      "trifusion":"true",
      "level":"64",
      "cutoff":"200"
   },
   "Momunofu":{
      "trifusion":"false",
      "level":"19",
      "cutoff":"37"
   },
   "Morrighan":{
      "trifusion":"true",
      "level":"62",
      "cutoff":"200"
   },
   "Mot":{
      "trifusion":"false",
      "level":"85",
      "cutoff":"169"
   },
   "Mothman":{
      "trifusion":"false",
      "level":"40",
      "cutoff":"79"
   },
   "Mou-Ryo":{
      "trifusion":"false",
      "level":"11",
      "cutoff":"21"
   },
   "Naga":{
      "trifusion":"false",
      "level":"24",
      "cutoff":"47"
   },
   "Nandi":{
      "trifusion":"false",
      "level":"44",
      "cutoff":"87"
   },
   "Narasimha":{
      "trifusion":"false",
      "level":"61",
      "cutoff":"200"
   },
   "Nekomata":{
      "trifusion":"false",
      "level":"26",
      "cutoff":"51"
   },
   "Nidhoggr":{
      "trifusion":"false",
      "level":"57",
      "cutoff":"200"
   },
   "Nozuchi":{
      "trifusion":"false",
      "level":"14",
      "cutoff":"27"
   },
   "Nue":{
      "trifusion":"false",
      "level":"37",
      "cutoff":"73"
   },
   "Nyarlathotep":{
      "trifusion":"true",
      "level":"86",
      "cutoff":"200"
   },
   "Oberon":{
      "trifusion":"false",
      "level":"52",
      "cutoff":"103"
   },
   "Ocypete":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Odin":{
      "trifusion":"true",
      "level":"70",
      "cutoff":"200"
   },
   "Ogre":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Okuninushi":{
      "trifusion":"false",
      "level":"59",
      "cutoff":"117"
   },
   "Omoikane":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Onamuchi":{
      "trifusion":"false",
      "level":"42",
      "cutoff":"83"
   },
   "Ongyu-Ki":{
      "trifusion":"true",
      "level":"91",
      "cutoff":"200"
   },
   "Oni":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Onkot":{
      "trifusion":"false",
      "level":"37",
      "cutoff":"73"
   },
   "Onmoraki":{
      "trifusion":"false",
      "level":"1",
      "cutoff":"1"
   },
   "Orobas":{
      "trifusion":"false",
      "level":"65",
      "cutoff":"129"
   },
   "Orthrus":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Ose":{
      "trifusion":"false",
      "level":"73",
      "cutoff":"200"
   },
   "Pa Bil Sag":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Pallas Athena":{
      "trifusion":"true",
      "level":"76",
      "cutoff":"200"
   },
   "Parvati":{
      "trifusion":"false",
      "level":"64",
      "cutoff":"127"
   },
   "Pazuzu":{
      "trifusion":"false",
      "level":"82",
      "cutoff":"163"
   },
   "Phantom":{
      "trifusion":"true",
      "level":"93",
      "cutoff":"200"
   },
   "Phoenix":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Pisaca":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Pixie":{
      "trifusion":"false",
      "level":"2",
      "cutoff":"5"
   },
   "Poltergeist":{
      "trifusion":"false",
      "level":"4",
      "cutoff":"7"
   },
   "Power":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Principality":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Pyro Jack":{
      "trifusion":"false",
      "level":"20",
      "cutoff":"39"
   },
   "Qing-Long":{
      "trifusion":"true",
      "level":"77",
      "cutoff":"200"
   },
   "Queen Mab":{
      "trifusion":"false",
      "level":"57",
      "cutoff":"113"
   },
   "Quetzalcoatl":{
      "trifusion":"false",
      "level":"55",
      "cutoff":"109"
   },
   "Raiju":{
      "trifusion":"false",
      "level":"31",
      "cutoff":"61"
   },
   "Raja Naga":{
      "trifusion":"false",
      "level":"40",
      "cutoff":"200"
   },
   "Rakshasa":{
      "trifusion":"false",
      "level":"41",
      "cutoff":"81"
   },
   "Raphael":{
      "trifusion":"true",
      "level":"93",
      "cutoff":"200"
   },
   "Sarasvati":{
      "trifusion":"false",
      "level":"30",
      "cutoff":"59"
   },
   "Sati":{
      "trifusion":"false",
      "level":"55",
      "cutoff":"109"
   },
   "Scathach":{
      "trifusion":"false",
      "level":"68",
      "cutoff":"135"
   },
   "Senri":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Setanta":{
      "trifusion":"false",
      "level":"28",
      "cutoff":"55"
   },
   "Shadow":{
      "trifusion":"false",
      "level":"52",
      "cutoff":"103"
   },
   "Shiisaa":{
      "trifusion":"false",
      "level":"13",
      "cutoff":"25"
   },
   "Shiki Ouji":{
      "trifusion":"false",
      "level":"63",
      "cutoff":"125"
   },
   "Shikigami":{
      "trifusion":"false",
      "level":"5",
      "cutoff":"9"
   },
   "Skadi":{
      "trifusion":"false",
      "level":"74",
      "cutoff":"200"
   },
   "Sleipnir":{
      "trifusion":"false",
      "level":"62",
      "cutoff":"200"
   },
   "Slime":{
      "trifusion":"false",
      "level":"6",
      "cutoff":"11"
   },
   "Sparna":{
      "trifusion":"false",
      "level":"42",
      "cutoff":"83"
   },
   "Specter":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Succubus":{
      "trifusion":"false",
      "level":"37",
      "cutoff":"73"
   },
   "Sudama":{
      "trifusion":"false",
      "level":"17",
      "cutoff":"33"
   },
   "Sui-Ki":{
      "trifusion":"false",
      "level":"69",
      "cutoff":"137"
   },
   "Surt":{
      "trifusion":"true",
      "level":"72",
      "cutoff":"200"
   },
   "Take-Mikazuchi":{
      "trifusion":"false",
      "level":"71",
      "cutoff":"200"
   },
   "Tan-Ki":{
      "trifusion":"false",
      "level":"37",
      "cutoff":"73"
   },
   "Tao Tie":{
      "trifusion":"false",
      "level":"65",
      "cutoff":"129"
   },
   "Tao Wu":{
      "trifusion":"false",
      "level":"64",
      "cutoff":"200"
   },
   "Taraka":{
      "trifusion":"false",
      "level":"25",
      "cutoff":"49"
   },
   "Tarasque":{
      "trifusion":"false",
      "level":"17",
      "cutoff":"33"
   },
   "Thor":{
      "trifusion":"true",
      "level":"76",
      "cutoff":"200"
   },
   "Thoth":{
      "trifusion":"true",
      "level":"42",
      "cutoff":"200"
   },
   "Throne":{
      "trifusion":"false",
      "level":"71",
      "cutoff":"200"
   },
   "Titan":{
      "trifusion":"false",
      "level":"62",
      "cutoff":"200"
   },
   "Titania":{
      "trifusion":"false",
      "level":"57",
      "cutoff":"200"
   },
   "Troll":{
      "trifusion":"false",
      "level":"38",
      "cutoff":"75"
   },
   "Turdak":{
      "trifusion":"false",
      "level":"23",
      "cutoff":"45"
   },
   "Typhon":{
      "trifusion":"false",
      "level":"51",
      "cutoff":"101"
   },
   "Ubelluris":{
      "trifusion":"false",
      "level":"41",
      "cutoff":"81"
   },
   "Unicorn":{
      "trifusion":"false",
      "level":"21",
      "cutoff":"41"
   },
   "Uriel":{
      "trifusion":"true",
      "level":"80",
      "cutoff":"160"
   },
   "Valkyrie":{
      "trifusion":"false",
      "level":"36",
      "cutoff":"71"
   },
   "Vetala":{
      "trifusion":"false",
      "level":"44",
      "cutoff":"200"
   },
   "Virtue":{
      "trifusion":"false",
      "level":"51",
      "cutoff":"101"
   },
   "Void":{
      "trifusion":"true",
      "level":"70",
      "cutoff":"200"
   },
   "Will O'Wisp":{
      "trifusion":"false",
      "level":"1",
      "cutoff":"1"
   },
   "Wu Kong":{
      "trifusion":"true",
      "level":"93",
      "cutoff":"200"
   },
   "Yakka":{
      "trifusion":"false",
      "level":"24",
      "cutoff":"47"
   },
   "Yaksa":{
      "trifusion":"false",
      "level":"51",
      "cutoff":"101"
   },
   "Yaksini":{
      "trifusion":"false",
      "level":"53",
      "cutoff":"105"
   },
   "Yata-Garasu":{
      "trifusion":"false",
      "level":"52",
      "cutoff":"103"
   },
   "Yomotsu-Ikusa":{
      "trifusion":"false",
      "level":"44",
      "cutoff":"87"
   },
   "Yomotsu-Shikome":{
      "trifusion":"false",
      "level":"35",
      "cutoff":"69"
   },
   "Zhen":{
      "trifusion":"false",
      "level":"41",
      "cutoff":"81"
   },
   "Zhu Que":{
      "trifusion":"true",
      "level":"49",
      "cutoff":"200"
   },
   "Zouchouten":{
      "trifusion":"false",
      "level":"38",
      "cutoff":"75"
   }
}