fusions =
{
   "Avian":{
      "Avian":"Aeros",
      "Beast":"Dragon King",
      "Brute":"Demigod",
      "Demigod":"Heavenly God",
      "Demon God":"-",
      "Destroyer":"Guardian",
      "Divine":"Dragon King",
      "Dragon":"Godly Beast",
      "Dragon King":"Heavenly God",
      "Earth Element":"Divine",
      "Earth Mother":"Dragon",
      "Element":"",
      "Evil Demon":"Raptor",
      "Evil Dragon":"X",
      "Fairy":"Wild Bird",
      "Fallen Angel":"Dragon King",
      "Femme":"Goddess",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Heavenly God",
      "Godly Beast":"Holy Beast",
      "Guardian":"Dragon",
      "Haunt":"X",
      "Heavenly God":"Dragon",
      "Holy Beast":"Earth Mother",
      "Nation Ruler":"Heavenly God",
      "Nocturne":"Femme",
      "Raptor":"X",
      "Reapers":"Raptor",
      "Seraph":"Divine",
      "Tyrant":"X",
      "Vile":"Reapers",
      "Wild Bird":"Raptor",
      "Wilder":"Wild Bird",
      "Yoma":"Nocturne"
   },
   "Beast":{
      "Avian":"Dragon King",
      "Beast":"Aeros",
      "Brute":"Femme",
      "Demigod":"Holy Beast",
      "Demon God":"-",
      "Destroyer":"Evil Dragon",
      "Divine":"Holy Beast",
      "Dragon":"Dragon King",
      "Dragon King":"Brute",
      "Earth Element":"Yoma",
      "Earth Mother":"Dragon King",
      "Element":"",
      "Evil Demon":"Wilder",
      "Evil Dragon":"Reapers",
      "Fairy":"Divine",
      "Fallen Angel":"Nocturne",
      "Femme":"Foul",
      "Fiend":"-",
      "Foul":"Wild Bird",
      "Goddess":"Holy Beast",
      "Godly Beast":"Dragon King",
      "Guardian":"Holy Beast",
      "Haunt":"Wilder",
      "Heavenly God":"Holy Beast",
      "Holy Beast":"Godly Beast",
      "Nation Ruler":"Dragon King",
      "Nocturne":"Holy Beast",
      "Raptor":"Wilder",
      "Reapers":"Wilder",
      "Seraph":"X",
      "Tyrant":"Nocturne",
      "Vile":"Foul",
      "Wild Bird":"Wilder",
      "Wilder":"Earth Element",
      "Yoma":"Fallen Angel"
   },
   "Brute":{
      "Avian":"Demigod",
      "Beast":"Femme",
      "Brute":"Erthys",
      "Demigod":"Divine",
      "Demon God":"-",
      "Destroyer":"Femme",
      "Divine":"Yoma",
      "Dragon":"Nocturne",
      "Dragon King":"Beast",
      "Earth Element":"Fairy",
      "Earth Mother":"Divine",
      "Element":"",
      "Evil Demon":"Haunt",
      "Evil Dragon":"Evil Demon",
      "Fairy":"Yoma",
      "Fallen Angel":"Earth Element",
      "Femme":"Beast",
      "Fiend":"-",
      "Foul":"Wilder",
      "Goddess":"Femme",
      "Godly Beast":"Evil Dragon",
      "Guardian":"Earth Element",
      "Haunt":"Foul",
      "Heavenly God":"Godly Beast",
      "Holy Beast":"Femme",
      "Nation Ruler":"Dragon King",
      "Nocturne":"Guardian",
      "Raptor":"Femme",
      "Reapers":"Earth Element",
      "Seraph":"X",
      "Tyrant":"Haunt",
      "Vile":"Foul",
      "Wild Bird":"Raptor",
      "Wilder":"Fairy",
      "Yoma":"Femme"
   },
   "Demigod":{
      "Avian":"Heavenly God",
      "Beast":"Holy Beast",
      "Brute":"Divine",
      "Demigod":"-",
      "Demon God":"-",
      "Destroyer":"Guardian",
      "Divine":"Goddess",
      "Dragon":"Holy Beast",
      "Dragon King":"Dragon",
      "Earth Element":"Earth Mother",
      "Earth Mother":"Femme",
      "Element":"",
      "Evil Demon":"Nation Ruler",
      "Evil Dragon":"Godly Beast",
      "Fairy":"X",
      "Fallen Angel":"Earth Mother",
      "Femme":"Nocturne",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Heavenly God",
      "Godly Beast":"Heavenly God",
      "Guardian":"Godly Beast",
      "Haunt":"X",
      "Heavenly God":"Dragon",
      "Holy Beast":"Godly Beast",
      "Nation Ruler":"Guardian",
      "Nocturne":"Holy Beast",
      "Raptor":"Holy Beast",
      "Reapers":"Haunt",
      "Seraph":"Goddess",
      "Tyrant":"Yoma",
      "Vile":"Nation Ruler",
      "Wild Bird":"Avian",
      "Wilder":"Yoma",
      "Yoma":"X"
   },
   "Demon God":{
      "Avian":"-",
      "Beast":"-",
      "Brute":"-",
      "Demigod":"-",
      "Demon God":"-",
      "Destroyer":"-",
      "Divine":"-",
      "Dragon":"-",
      "Dragon King":"-",
      "Earth Element":"-",
      "Earth Mother":"-",
      "Element":"",
      "Evil Demon":"-",
      "Evil Dragon":"-",
      "Fairy":"-",
      "Fallen Angel":"-",
      "Femme":"-",
      "Fiend":"-",
      "Foul":"-",
      "Goddess":"-",
      "Godly Beast":"-",
      "Guardian":"-",
      "Haunt":"-",
      "Heavenly God":"-",
      "Holy Beast":"-",
      "Nation Ruler":"-",
      "Nocturne":"-",
      "Raptor":"-",
      "Reapers":"-",
      "Seraph":"-",
      "Tyrant":"-",
      "Vile":"-",
      "Wild Bird":"-",
      "Wilder":"-",
      "Yoma":"-"
   },
   "Destroyer":{
      "Avian":"Guardian",
      "Beast":"Evil Dragon",
      "Brute":"Femme",
      "Demigod":"Guardian",
      "Demon God":"-",
      "Destroyer":"-",
      "Divine":"Vile",
      "Dragon":"Evil Dragon",
      "Dragon King":"Evil Dragon",
      "Earth Element":"Femme",
      "Earth Mother":"Vile",
      "Element":"",
      "Evil Demon":"X",
      "Evil Dragon":"X",
      "Fairy":"Brute",
      "Fallen Angel":"Vile",
      "Femme":"X",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Femme",
      "Godly Beast":"Holy Beast",
      "Guardian":"Earth Mother",
      "Haunt":"X",
      "Heavenly God":"Nation Ruler",
      "Holy Beast":"Guardian",
      "Nation Ruler":"Dragon",
      "Nocturne":"Earth Mother",
      "Raptor":"Evil Dragon",
      "Reapers":"Dragon",
      "Seraph":"Vile",
      "Tyrant":"Earth Mother",
      "Vile":"Reapers",
      "Wild Bird":"Earth Mother",
      "Wilder":"Dragon",
      "Yoma":"Demigod"
   },
   "Divine":{
      "Avian":"Dragon King",
      "Beast":"Holy Beast",
      "Brute":"Yoma",
      "Demigod":"Goddess",
      "Demon God":"-",
      "Destroyer":"Vile",
      "Divine":"Aeros",
      "Dragon":"Goddess",
      "Dragon King":"Fairy",
      "Earth Element":"Nocturne",
      "Earth Mother":"Goddess",
      "Element":"",
      "Evil Demon":"Reapers",
      "Evil Dragon":"Wild Bird",
      "Fairy":"Goddess",
      "Fallen Angel":"X",
      "Femme":"Beast",
      "Fiend":"-",
      "Foul":"Fallen Angel",
      "Goddess":"Heavenly God",
      "Godly Beast":"Goddess",
      "Guardian":"Earth Mother",
      "Haunt":"Earth Element",
      "Heavenly God":"Avian",
      "Holy Beast":"Goddess",
      "Nation Ruler":"Wild Bird",
      "Nocturne":"Dragon King",
      "Raptor":"Wild Bird",
      "Reapers":"Raptor",
      "Seraph":"Goddess",
      "Tyrant":"Vile",
      "Vile":"Reapers",
      "Wild Bird":"Fairy",
      "Wilder":"Fallen Angel",
      "Yoma":"Dragon King"
   },
   "Dragon":{
      "Avian":"Godly Beast",
      "Beast":"Dragon King",
      "Brute":"Nocturne",
      "Demigod":"Holy Beast",
      "Demon God":"-",
      "Destroyer":"Evil Dragon",
      "Divine":"Goddess",
      "Dragon":"Evil Dragon",
      "Dragon King":"Earth Mother",
      "Earth Element":"Nation Ruler",
      "Earth Mother":"X",
      "Element":"",
      "Evil Demon":"Guardian",
      "Evil Dragon":"X",
      "Fairy":"Demigod",
      "Fallen Angel":"Dragon King",
      "Femme":"Nocturne",
      "Fiend":"-",
      "Foul":"Dragon King",
      "Goddess":"Godly Beast",
      "Godly Beast":"Demigod",
      "Guardian":"Nation Ruler",
      "Haunt":"X",
      "Heavenly God":"Holy Beast",
      "Holy Beast":"Dragon King",
      "Nation Ruler":"Earth Mother",
      "Nocturne":"Femme",
      "Raptor":"Wilder",
      "Reapers":"Evil Dragon",
      "Seraph":"Holy Beast",
      "Tyrant":"Evil Dragon",
      "Vile":"Dragon King",
      "Wild Bird":"Heavenly God",
      "Wilder":"Femme",
      "Yoma":"Godly Beast"
   },
   "Dragon King":{
      "Avian":"Heavenly God",
      "Beast":"Brute",
      "Brute":"Beast",
      "Demigod":"Dragon",
      "Demon God":"-",
      "Destroyer":"Evil Dragon",
      "Divine":"Fairy",
      "Dragon":"Earth Mother",
      "Dragon King":"Aquans",
      "Earth Element":"Fallen Angel",
      "Earth Mother":"Femme",
      "Element":"",
      "Evil Demon":"Evil Dragon",
      "Evil Dragon":"Evil Demon",
      "Fairy":"Yoma",
      "Fallen Angel":"Demigod",
      "Femme":"Demigod",
      "Fiend":"-",
      "Foul":"Fallen Angel",
      "Goddess":"Fairy",
      "Godly Beast":"Dragon",
      "Guardian":"Dragon",
      "Haunt":"Brute",
      "Heavenly God":"Goddess",
      "Holy Beast":"Guardian",
      "Nation Ruler":"Earth Mother",
      "Nocturne":"Fallen Angel",
      "Raptor":"Foul",
      "Reapers":"Evil Dragon",
      "Seraph":"X",
      "Tyrant":"Evil Dragon",
      "Vile":"Guardian",
      "Wild Bird":"Beast",
      "Wilder":"Nocturne",
      "Yoma":"Nocturne"
   },
   "Earth Element":{
      "Avian":"Divine",
      "Beast":"Yoma",
      "Brute":"Fairy",
      "Demigod":"Earth Mother",
      "Demon God":"-",
      "Destroyer":"Femme",
      "Divine":"Nocturne",
      "Dragon":"Nation Ruler",
      "Dragon King":"Fallen Angel",
      "Earth Element":"Erthys",
      "Earth Mother":"Beast",
      "Element":"",
      "Evil Demon":"Beast",
      "Evil Dragon":"Evil Demon",
      "Fairy":"Wilder",
      "Fallen Angel":"Yoma",
      "Femme":"Wilder",
      "Fiend":"-",
      "Foul":"Femme",
      "Goddess":"Earth Mother",
      "Godly Beast":"Nation Ruler",
      "Guardian":"Dragon King",
      "Haunt":"Foul",
      "Heavenly God":"Nation Ruler",
      "Holy Beast":"Beast",
      "Nation Ruler":"Dragon King",
      "Nocturne":"Foul",
      "Raptor":"Foul",
      "Reapers":"Evil Demon",
      "Seraph":"Heavenly God",
      "Tyrant":"Wilder",
      "Vile":"Haunt",
      "Wild Bird":"Fairy",
      "Wilder":"Brute",
      "Yoma":"Wilder"
   },
   "Earth Mother":{
      "Avian":"Dragon",
      "Beast":"Dragon King",
      "Brute":"Divine",
      "Demigod":"Femme",
      "Demon God":"-",
      "Destroyer":"Vile",
      "Divine":"Goddess",
      "Dragon":"X",
      "Dragon King":"Femme",
      "Earth Element":"Beast",
      "Earth Mother":"Erthys",
      "Element":"",
      "Evil Demon":"Guardian",
      "Evil Dragon":"Earth Element",
      "Fairy":"Yoma",
      "Fallen Angel":"Femme",
      "Femme":"Guardian",
      "Fiend":"-",
      "Foul":"Earth Element",
      "Goddess":"X",
      "Godly Beast":"Avian",
      "Guardian":"Femme",
      "Haunt":"Femme",
      "Heavenly God":"Goddess",
      "Holy Beast":"Godly Beast",
      "Nation Ruler":"Guardian",
      "Nocturne":"Guardian",
      "Raptor":"Dragon King",
      "Reapers":"X",
      "Seraph":"Heavenly God",
      "Tyrant":"X",
      "Vile":"Reapers",
      "Wild Bird":"Avian",
      "Wilder":"Haunt",
      "Yoma":"Nocturne"
   },
   "Element":{
      "Avian":"",
      "Beast":"",
      "Brute":"",
      "Demigod":"",
      "Demon God":"",
      "Destroyer":"",
      "Divine":"",
      "Dragon":"",
      "Dragon King":"",
      "Earth Element":"",
      "Earth Mother":"",
      "Element":"",
      "Evil Demon":"",
      "Evil Dragon":"",
      "Fairy":"",
      "Fallen Angel":"",
      "Femme":"",
      "Fiend":"",
      "Foul":"",
      "Goddess":"",
      "Godly Beast":"",
      "Guardian":"",
      "Haunt":"",
      "Heavenly God":"",
      "Holy Beast":"",
      "Nation Ruler":"",
      "Nocturne":"",
      "Raptor":"",
      "Reapers":"",
      "Seraph":"",
      "Tyrant":"",
      "Vile":"",
      "Wild Bird":"",
      "Wilder":"",
      "Yoma":""
   },
   "Evil Demon":{
      "Avian":"Raptor",
      "Beast":"Wilder",
      "Brute":"Haunt",
      "Demigod":"Nation Ruler",
      "Demon God":"-",
      "Destroyer":"X",
      "Divine":"Reapers",
      "Dragon":"Guardian",
      "Dragon King":"Evil Dragon",
      "Earth Element":"Beast",
      "Earth Mother":"Guardian",
      "Element":"",
      "Evil Demon":"-",
      "Evil Dragon":"Vile",
      "Fairy":"Brute",
      "Fallen Angel":"Evil Dragon",
      "Femme":"Beast",
      "Fiend":"-",
      "Foul":"Brute",
      "Goddess":"Femme",
      "Godly Beast":"X",
      "Guardian":"Brute",
      "Haunt":"Foul",
      "Heavenly God":"Vile",
      "Holy Beast":"Raptor",
      "Nation Ruler":"Vile",
      "Nocturne":"Fallen Angel",
      "Raptor":"Foul",
      "Reapers":"Vile",
      "Seraph":"X",
      "Tyrant":"Foul",
      "Vile":"Foul",
      "Wild Bird":"Brute",
      "Wilder":"Brute",
      "Yoma":"Earth Element"
   },
   "Evil Dragon":{
      "Avian":"X",
      "Beast":"Reapers",
      "Brute":"Evil Demon",
      "Demigod":"Godly Beast",
      "Demon God":"-",
      "Destroyer":"X",
      "Divine":"Wild Bird",
      "Dragon":"X",
      "Dragon King":"Evil Demon",
      "Earth Element":"Evil Demon",
      "Earth Mother":"Earth Element",
      "Element":"",
      "Evil Demon":"Vile",
      "Evil Dragon":"X",
      "Fairy":"Dragon King",
      "Fallen Angel":"Evil Demon",
      "Femme":"Evil Demon",
      "Fiend":"-",
      "Foul":"Vile",
      "Goddess":"Vile",
      "Godly Beast":"X",
      "Guardian":"Vile",
      "Haunt":"Raptor",
      "Heavenly God":"X",
      "Holy Beast":"Reapers",
      "Nation Ruler":"Reapers",
      "Nocturne":"Fallen Angel",
      "Raptor":"Wilder",
      "Reapers":"Wilder",
      "Seraph":"X",
      "Tyrant":"Vile",
      "Vile":"Wilder",
      "Wild Bird":"Raptor",
      "Wilder":"Reapers",
      "Yoma":"Dragon King"
   },
   "Fairy":{
      "Avian":"Wild Bird",
      "Beast":"Divine",
      "Brute":"Yoma",
      "Demigod":"X",
      "Demon God":"-",
      "Destroyer":"Brute",
      "Divine":"Goddess",
      "Dragon":"Demigod",
      "Dragon King":"Yoma",
      "Earth Element":"Wilder",
      "Earth Mother":"Yoma",
      "Element":"",
      "Evil Demon":"Brute",
      "Evil Dragon":"Dragon King",
      "Fairy":"Aeros",
      "Fallen Angel":"Yoma",
      "Femme":"Haunt",
      "Fiend":"-",
      "Foul":"Haunt",
      "Goddess":"Demigod",
      "Godly Beast":"Divine",
      "Guardian":"Brute",
      "Haunt":"Wild Bird",
      "Heavenly God":"Divine",
      "Holy Beast":"Goddess",
      "Nation Ruler":"Dragon King",
      "Nocturne":"X",
      "Raptor":"Haunt",
      "Reapers":"Nocturne",
      "Seraph":"Holy Beast",
      "Tyrant":"Nocturne",
      "Vile":"Raptor",
      "Wild Bird":"Divine",
      "Wilder":"Wild Bird",
      "Yoma":"Earth Element"
   },
   "Fallen Angel":{
      "Avian":"Dragon King",
      "Beast":"Nocturne",
      "Brute":"Earth Element",
      "Demigod":"Earth Mother",
      "Demon God":"-",
      "Destroyer":"Vile",
      "Divine":"X",
      "Dragon":"Dragon King",
      "Dragon King":"Demigod",
      "Earth Element":"Yoma",
      "Earth Mother":"Femme",
      "Element":"",
      "Evil Demon":"Evil Dragon",
      "Evil Dragon":"Evil Demon",
      "Fairy":"Yoma",
      "Fallen Angel":"-",
      "Femme":"Wilder",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Divine",
      "Godly Beast":"Divine",
      "Guardian":"Nocturne",
      "Haunt":"Yoma",
      "Heavenly God":"Earth Mother",
      "Holy Beast":"Beast",
      "Nation Ruler":"Dragon King",
      "Nocturne":"Fairy",
      "Raptor":"Foul",
      "Reapers":"Raptor",
      "Seraph":"Earth Mother",
      "Tyrant":"X",
      "Vile":"Brute",
      "Wild Bird":"Raptor",
      "Wilder":"Nocturne",
      "Yoma":"Earth Element"
   },
   "Femme":{
      "Avian":"Goddess",
      "Beast":"Foul",
      "Brute":"Beast",
      "Demigod":"Nocturne",
      "Demon God":"-",
      "Destroyer":"X",
      "Divine":"Beast",
      "Dragon":"Nocturne",
      "Dragon King":"Demigod",
      "Earth Element":"Wilder",
      "Earth Mother":"Guardian",
      "Element":"",
      "Evil Demon":"Beast",
      "Evil Dragon":"Evil Demon",
      "Fairy":"Haunt",
      "Fallen Angel":"Wilder",
      "Femme":"-",
      "Fiend":"-",
      "Foul":"Wilder",
      "Goddess":"Earth Mother",
      "Godly Beast":"Guardian",
      "Guardian":"Earth Mother",
      "Haunt":"Foul",
      "Heavenly God":"Fallen Angel",
      "Holy Beast":"Earth Mother",
      "Nation Ruler":"Guardian",
      "Nocturne":"Evil Demon",
      "Raptor":"Foul",
      "Reapers":"Evil Demon",
      "Seraph":"X",
      "Tyrant":"Earth Mother",
      "Vile":"Brute",
      "Wild Bird":"Evil Demon",
      "Wilder":"Fallen Angel",
      "Yoma":"Brute"
   },
   "Fiend":{
      "Avian":"-",
      "Beast":"-",
      "Brute":"-",
      "Demigod":"-",
      "Demon God":"-",
      "Destroyer":"-",
      "Divine":"-",
      "Dragon":"-",
      "Dragon King":"-",
      "Earth Element":"-",
      "Earth Mother":"-",
      "Element":"",
      "Evil Demon":"-",
      "Evil Dragon":"-",
      "Fairy":"-",
      "Fallen Angel":"-",
      "Femme":"-",
      "Fiend":"-",
      "Foul":"-",
      "Goddess":"-",
      "Godly Beast":"-",
      "Guardian":"-",
      "Haunt":"-",
      "Heavenly God":"-",
      "Holy Beast":"-",
      "Nation Ruler":"-",
      "Nocturne":"-",
      "Raptor":"-",
      "Reapers":"-",
      "Seraph":"-",
      "Tyrant":"-",
      "Vile":"-",
      "Wild Bird":"-",
      "Wilder":"-",
      "Yoma":"-"
   },
   "Foul":{
      "Avian":"X",
      "Beast":"Wild Bird",
      "Brute":"Wilder",
      "Demigod":"X",
      "Demon God":"-",
      "Destroyer":"X",
      "Divine":"Fallen Angel",
      "Dragon":"Dragon King",
      "Dragon King":"Fallen Angel",
      "Earth Element":"Femme",
      "Earth Mother":"Earth Element",
      "Element":"",
      "Evil Demon":"Brute",
      "Evil Dragon":"Vile",
      "Fairy":"Haunt",
      "Fallen Angel":"X",
      "Femme":"Wilder",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"X",
      "Godly Beast":"X",
      "Guardian":"Evil Dragon",
      "Haunt":"Brute",
      "Heavenly God":"Haunt",
      "Holy Beast":"X",
      "Nation Ruler":"X",
      "Nocturne":"Brute",
      "Raptor":"X",
      "Reapers":"X",
      "Seraph":"Fallen Angel",
      "Tyrant":"Haunt",
      "Vile":"Haunt",
      "Wild Bird":"X",
      "Wilder":"Wild Bird",
      "Yoma":"Wild Bird"
   },
   "Goddess":{
      "Avian":"Heavenly God",
      "Beast":"Holy Beast",
      "Brute":"Femme",
      "Demigod":"Heavenly God",
      "Demon God":"-",
      "Destroyer":"Femme",
      "Divine":"Heavenly God",
      "Dragon":"Godly Beast",
      "Dragon King":"Fairy",
      "Earth Element":"Earth Mother",
      "Earth Mother":"X",
      "Element":"",
      "Evil Demon":"Femme",
      "Evil Dragon":"Vile",
      "Fairy":"Demigod",
      "Fallen Angel":"Divine",
      "Femme":"Earth Mother",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"X",
      "Godly Beast":"Beast",
      "Guardian":"Earth Mother",
      "Haunt":"Vile",
      "Heavenly God":"X",
      "Holy Beast":"Godly Beast",
      "Nation Ruler":"Earth Mother",
      "Nocturne":"Fallen Angel",
      "Raptor":"Fallen Angel",
      "Reapers":"Vile",
      "Seraph":"Earth Mother",
      "Tyrant":"X",
      "Vile":"Reapers",
      "Wild Bird":"Avian",
      "Wilder":"Beast",
      "Yoma":"Femme"
   },
   "Godly Beast":{
      "Avian":"Holy Beast",
      "Beast":"Dragon King",
      "Brute":"Evil Dragon",
      "Demigod":"Heavenly God",
      "Demon God":"-",
      "Destroyer":"Holy Beast",
      "Divine":"Goddess",
      "Dragon":"Demigod",
      "Dragon King":"Dragon",
      "Earth Element":"Nation Ruler",
      "Earth Mother":"Avian",
      "Element":"",
      "Evil Demon":"X",
      "Evil Dragon":"X",
      "Fairy":"Divine",
      "Fallen Angel":"Divine",
      "Femme":"Guardian",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Beast",
      "Godly Beast":"Flaemis",
      "Guardian":"Holy Beast",
      "Haunt":"X",
      "Heavenly God":"Dragon",
      "Holy Beast":"Goddess",
      "Nation Ruler":"Dragon",
      "Nocturne":"Holy Beast",
      "Raptor":"Wilder",
      "Reapers":"Vile",
      "Seraph":"Avian",
      "Tyrant":"X",
      "Vile":"Evil Dragon",
      "Wild Bird":"Avian",
      "Wilder":"X",
      "Yoma":"Divine"
   },
   "Guardian":{
      "Avian":"Dragon",
      "Beast":"Holy Beast",
      "Brute":"Earth Element",
      "Demigod":"Godly Beast",
      "Demon God":"-",
      "Destroyer":"Earth Mother",
      "Divine":"Earth Mother",
      "Dragon":"Nation Ruler",
      "Dragon King":"Dragon",
      "Earth Element":"Dragon King",
      "Earth Mother":"Femme",
      "Element":"",
      "Evil Demon":"Brute",
      "Evil Dragon":"Vile",
      "Fairy":"Brute",
      "Fallen Angel":"Nocturne",
      "Femme":"Earth Mother",
      "Fiend":"-",
      "Foul":"Evil Dragon",
      "Goddess":"Earth Mother",
      "Godly Beast":"Holy Beast",
      "Guardian":"-",
      "Haunt":"X",
      "Heavenly God":"Nation Ruler",
      "Holy Beast":"Nation Ruler",
      "Nation Ruler":"X",
      "Nocturne":"Femme",
      "Raptor":"Vile",
      "Reapers":"Evil Demon",
      "Seraph":"Nation Ruler",
      "Tyrant":"Dragon",
      "Vile":"Reapers",
      "Wild Bird":"Femme",
      "Wilder":"X",
      "Yoma":"Nation Ruler"
   },
   "Haunt":{
      "Avian":"X",
      "Beast":"Wilder",
      "Brute":"Foul",
      "Demigod":"X",
      "Demon God":"-",
      "Destroyer":"X",
      "Divine":"Earth Element",
      "Dragon":"X",
      "Dragon King":"Brute",
      "Earth Element":"Foul",
      "Earth Mother":"Femme",
      "Element":"",
      "Evil Demon":"Foul",
      "Evil Dragon":"Raptor",
      "Fairy":"Wild Bird",
      "Fallen Angel":"Yoma",
      "Femme":"Foul",
      "Fiend":"-",
      "Foul":"Brute",
      "Goddess":"Vile",
      "Godly Beast":"X",
      "Guardian":"X",
      "Haunt":"X",
      "Heavenly God":"X",
      "Holy Beast":"Wild Bird",
      "Nation Ruler":"Brute",
      "Nocturne":"Yoma",
      "Raptor":"Wild Bird",
      "Reapers":"X",
      "Seraph":"Fallen Angel",
      "Tyrant":"Foul",
      "Vile":"Foul",
      "Wild Bird":"Yoma",
      "Wilder":"Earth Element",
      "Yoma":"Earth Element"
   },
   "Heavenly God":{
      "Avian":"Dragon",
      "Beast":"Holy Beast",
      "Brute":"Godly Beast",
      "Demigod":"Dragon",
      "Demon God":"-",
      "Destroyer":"Nation Ruler",
      "Divine":"Avian",
      "Dragon":"Holy Beast",
      "Dragon King":"Goddess",
      "Earth Element":"Nation Ruler",
      "Earth Mother":"Goddess",
      "Element":"",
      "Evil Demon":"Vile",
      "Evil Dragon":"X",
      "Fairy":"Divine",
      "Fallen Angel":"Earth Mother",
      "Femme":"Fallen Angel",
      "Fiend":"-",
      "Foul":"Haunt",
      "Goddess":"X",
      "Godly Beast":"Dragon",
      "Guardian":"Nation Ruler",
      "Haunt":"X",
      "Heavenly God":"-",
      "Holy Beast":"Godly Beast",
      "Nation Ruler":"X",
      "Nocturne":"Fallen Angel",
      "Raptor":"Nocturne",
      "Reapers":"X",
      "Seraph":"Nation Ruler",
      "Tyrant":"X",
      "Vile":"X",
      "Wild Bird":"Avian",
      "Wilder":"Femme",
      "Yoma":"Goddess"
   },
   "Holy Beast":{
      "Avian":"Earth Mother",
      "Beast":"Godly Beast",
      "Brute":"Femme",
      "Demigod":"Godly Beast",
      "Demon God":"-",
      "Destroyer":"Guardian",
      "Divine":"Goddess",
      "Dragon":"Dragon King",
      "Dragon King":"Guardian",
      "Earth Element":"Beast",
      "Earth Mother":"Godly Beast",
      "Element":"",
      "Evil Demon":"Raptor",
      "Evil Dragon":"Reapers",
      "Fairy":"Goddess",
      "Fallen Angel":"Beast",
      "Femme":"Earth Mother",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Godly Beast",
      "Godly Beast":"Goddess",
      "Guardian":"Nation Ruler",
      "Haunt":"Wild Bird",
      "Heavenly God":"Godly Beast",
      "Holy Beast":"Flaemis",
      "Nation Ruler":"Earth Element",
      "Nocturne":"Earth Mother",
      "Raptor":"Avian",
      "Reapers":"X",
      "Seraph":"Godly Beast",
      "Tyrant":"Evil Dragon",
      "Vile":"X",
      "Wild Bird":"Avian",
      "Wilder":"X",
      "Yoma":"Divine"
   },
   "Nation Ruler":{
      "Avian":"Heavenly God",
      "Beast":"Dragon King",
      "Brute":"Dragon King",
      "Demigod":"Guardian",
      "Demon God":"-",
      "Destroyer":"Dragon",
      "Divine":"Wild Bird",
      "Dragon":"Earth Mother",
      "Dragon King":"Earth Mother",
      "Earth Element":"Dragon King",
      "Earth Mother":"Guardian",
      "Element":"",
      "Evil Demon":"Vile",
      "Evil Dragon":"Reapers",
      "Fairy":"Dragon King",
      "Fallen Angel":"Dragon King",
      "Femme":"Guardian",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Earth Mother",
      "Godly Beast":"Dragon",
      "Guardian":"X",
      "Haunt":"Brute",
      "Heavenly God":"X",
      "Holy Beast":"Earth Element",
      "Nation Ruler":"Erthys",
      "Nocturne":"Earth Mother",
      "Raptor":"Reapers",
      "Reapers":"Vile",
      "Seraph":"Dragon",
      "Tyrant":"Guardian",
      "Vile":"Reapers",
      "Wild Bird":"Earth Mother",
      "Wilder":"Godly Beast",
      "Yoma":"Femme"
   },
   "Nocturne":{
      "Avian":"Femme",
      "Beast":"Holy Beast",
      "Brute":"Guardian",
      "Demigod":"Holy Beast",
      "Demon God":"-",
      "Destroyer":"Earth Mother",
      "Divine":"Dragon King",
      "Dragon":"Femme",
      "Dragon King":"Fallen Angel",
      "Earth Element":"Foul",
      "Earth Mother":"Guardian",
      "Element":"",
      "Evil Demon":"Fallen Angel",
      "Evil Dragon":"Fallen Angel",
      "Fairy":"X",
      "Fallen Angel":"Fairy",
      "Femme":"Evil Demon",
      "Fiend":"-",
      "Foul":"Brute",
      "Goddess":"Fallen Angel",
      "Godly Beast":"Holy Beast",
      "Guardian":"Femme",
      "Haunt":"Yoma",
      "Heavenly God":"Fallen Angel",
      "Holy Beast":"Earth Mother",
      "Nation Ruler":"Earth Mother",
      "Nocturne":"Erthys",
      "Raptor":"Wild Bird",
      "Reapers":"Fallen Angel",
      "Seraph":"Fallen Angel",
      "Tyrant":"Earth Mother",
      "Vile":"Haunt",
      "Wild Bird":"Brute",
      "Wilder":"Beast",
      "Yoma":"Divine"
   },
   "Raptor":{
      "Avian":"X",
      "Beast":"Wilder",
      "Brute":"Femme",
      "Demigod":"Holy Beast",
      "Demon God":"-",
      "Destroyer":"Evil Dragon",
      "Divine":"Wild Bird",
      "Dragon":"Wilder",
      "Dragon King":"Foul",
      "Earth Element":"Foul",
      "Earth Mother":"Dragon King",
      "Element":"",
      "Evil Demon":"Foul",
      "Evil Dragon":"Wilder",
      "Fairy":"Haunt",
      "Fallen Angel":"Foul",
      "Femme":"Foul",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Fallen Angel",
      "Godly Beast":"Wilder",
      "Guardian":"Vile",
      "Haunt":"Wild Bird",
      "Heavenly God":"Nocturne",
      "Holy Beast":"Avian",
      "Nation Ruler":"Reapers",
      "Nocturne":"Wild Bird",
      "Raptor":"-",
      "Reapers":"Evil Dragon",
      "Seraph":"Reapers",
      "Tyrant":"Dragon",
      "Vile":"Evil Dragon",
      "Wild Bird":"X",
      "Wilder":"Wild Bird",
      "Yoma":"Evil Demon"
   },
   "Reapers":{
      "Avian":"Raptor",
      "Beast":"Wilder",
      "Brute":"Earth Element",
      "Demigod":"Haunt",
      "Demon God":"-",
      "Destroyer":"Dragon",
      "Divine":"Raptor",
      "Dragon":"Evil Dragon",
      "Dragon King":"Evil Dragon",
      "Earth Element":"Evil Demon",
      "Earth Mother":"X",
      "Element":"",
      "Evil Demon":"Vile",
      "Evil Dragon":"Wilder",
      "Fairy":"Nocturne",
      "Fallen Angel":"Raptor",
      "Femme":"Evil Demon",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Vile",
      "Godly Beast":"Vile",
      "Guardian":"Evil Demon",
      "Haunt":"X",
      "Heavenly God":"X",
      "Holy Beast":"X",
      "Nation Ruler":"Vile",
      "Nocturne":"Fallen Angel",
      "Raptor":"Evil Dragon",
      "Reapers":"X",
      "Seraph":"X",
      "Tyrant":"Vile",
      "Vile":"Foul",
      "Wild Bird":"Raptor",
      "Wilder":"Raptor",
      "Yoma":"Earth Element"
   },
   "Seraph":{
      "Avian":"Divine",
      "Beast":"X",
      "Brute":"X",
      "Demigod":"Goddess",
      "Demon God":"-",
      "Destroyer":"Vile",
      "Divine":"Goddess",
      "Dragon":"Holy Beast",
      "Dragon King":"X",
      "Earth Element":"Heavenly God",
      "Earth Mother":"Heavenly God",
      "Element":"",
      "Evil Demon":"X",
      "Evil Dragon":"X",
      "Fairy":"Holy Beast",
      "Fallen Angel":"Earth Mother",
      "Femme":"X",
      "Fiend":"-",
      "Foul":"Fallen Angel",
      "Goddess":"Earth Mother",
      "Godly Beast":"Avian",
      "Guardian":"Nation Ruler",
      "Haunt":"Fallen Angel",
      "Heavenly God":"Nation Ruler",
      "Holy Beast":"Godly Beast",
      "Nation Ruler":"Dragon",
      "Nocturne":"Fallen Angel",
      "Raptor":"Reapers",
      "Reapers":"X",
      "Seraph":"X",
      "Tyrant":"Fallen Angel",
      "Vile":"Divine",
      "Wild Bird":"Avian",
      "Wilder":"X",
      "Yoma":"Goddess"
   },
   "Tyrant":{
      "Avian":"X",
      "Beast":"Nocturne",
      "Brute":"Haunt",
      "Demigod":"Yoma",
      "Demon God":"-",
      "Destroyer":"Earth Mother",
      "Divine":"Vile",
      "Dragon":"Evil Dragon",
      "Dragon King":"Evil Dragon",
      "Earth Element":"Wilder",
      "Earth Mother":"X",
      "Element":"",
      "Evil Demon":"Foul",
      "Evil Dragon":"Vile",
      "Fairy":"Nocturne",
      "Fallen Angel":"X",
      "Femme":"Earth Mother",
      "Fiend":"-",
      "Foul":"Haunt",
      "Goddess":"X",
      "Godly Beast":"X",
      "Guardian":"Dragon",
      "Haunt":"Foul",
      "Heavenly God":"X",
      "Holy Beast":"Evil Dragon",
      "Nation Ruler":"Guardian",
      "Nocturne":"Earth Mother",
      "Raptor":"Dragon",
      "Reapers":"Vile",
      "Seraph":"Fallen Angel",
      "Tyrant":"-",
      "Vile":"Reapers",
      "Wild Bird":"Evil Dragon",
      "Wilder":"Nocturne",
      "Yoma":"Nocturne"
   },
   "Vile":{
      "Avian":"Reapers",
      "Beast":"Foul",
      "Brute":"Foul",
      "Demigod":"Nation Ruler",
      "Demon God":"-",
      "Destroyer":"Reapers",
      "Divine":"Reapers",
      "Dragon":"Dragon King",
      "Dragon King":"Guardian",
      "Earth Element":"Haunt",
      "Earth Mother":"Reapers",
      "Element":"",
      "Evil Demon":"Foul",
      "Evil Dragon":"Wilder",
      "Fairy":"Raptor",
      "Fallen Angel":"Brute",
      "Femme":"Brute",
      "Fiend":"-",
      "Foul":"Haunt",
      "Goddess":"Reapers",
      "Godly Beast":"Evil Dragon",
      "Guardian":"Reapers",
      "Haunt":"Foul",
      "Heavenly God":"X",
      "Holy Beast":"X",
      "Nation Ruler":"Reapers",
      "Nocturne":"Haunt",
      "Raptor":"Evil Dragon",
      "Reapers":"Foul",
      "Seraph":"Divine",
      "Tyrant":"Reapers",
      "Vile":"-",
      "Wild Bird":"Evil Dragon",
      "Wilder":"Foul",
      "Yoma":"Earth Element"
   },
   "Wild Bird":{
      "Avian":"Raptor",
      "Beast":"Wilder",
      "Brute":"Raptor",
      "Demigod":"Avian",
      "Demon God":"-",
      "Destroyer":"Earth Mother",
      "Divine":"Fairy",
      "Dragon":"Heavenly God",
      "Dragon King":"Beast",
      "Earth Element":"Fairy",
      "Earth Mother":"Avian",
      "Element":"",
      "Evil Demon":"Brute",
      "Evil Dragon":"Raptor",
      "Fairy":"Divine",
      "Fallen Angel":"Raptor",
      "Femme":"Evil Demon",
      "Fiend":"-",
      "Foul":"X",
      "Goddess":"Avian",
      "Godly Beast":"Avian",
      "Guardian":"Femme",
      "Haunt":"Yoma",
      "Heavenly God":"Avian",
      "Holy Beast":"Avian",
      "Nation Ruler":"Earth Mother",
      "Nocturne":"Brute",
      "Raptor":"X",
      "Reapers":"Raptor",
      "Seraph":"Avian",
      "Tyrant":"Evil Dragon",
      "Vile":"Evil Dragon",
      "Wild Bird":"Aeros",
      "Wilder":"Foul",
      "Yoma":"Divine"
   },
   "Wilder":{
      "Avian":"Wild Bird",
      "Beast":"Earth Element",
      "Brute":"Fairy",
      "Demigod":"Yoma",
      "Demon God":"-",
      "Destroyer":"Dragon",
      "Divine":"Fallen Angel",
      "Dragon":"Femme",
      "Dragon King":"Nocturne",
      "Earth Element":"Brute",
      "Earth Mother":"Haunt",
      "Element":"",
      "Evil Demon":"Brute",
      "Evil Dragon":"Reapers",
      "Fairy":"Wild Bird",
      "Fallen Angel":"Nocturne",
      "Femme":"Fallen Angel",
      "Fiend":"-",
      "Foul":"Wild Bird",
      "Goddess":"Beast",
      "Godly Beast":"X",
      "Guardian":"X",
      "Haunt":"Earth Element",
      "Heavenly God":"Femme",
      "Holy Beast":"X",
      "Nation Ruler":"Godly Beast",
      "Nocturne":"Beast",
      "Raptor":"Wild Bird",
      "Reapers":"Raptor",
      "Seraph":"X",
      "Tyrant":"Nocturne",
      "Vile":"Foul",
      "Wild Bird":"Foul",
      "Wilder":"Aeros",
      "Yoma":"Evil Demon"
   },
   "Yoma":{
      "Avian":"Nocturne",
      "Beast":"Fallen Angel",
      "Brute":"Femme",
      "Demigod":"X",
      "Demon God":"-",
      "Destroyer":"Demigod",
      "Divine":"Dragon King",
      "Dragon":"Godly Beast",
      "Dragon King":"Nocturne",
      "Earth Element":"Wilder",
      "Earth Mother":"Nocturne",
      "Element":"",
      "Evil Demon":"Earth Element",
      "Evil Dragon":"Dragon King",
      "Fairy":"Earth Element",
      "Fallen Angel":"Earth Element",
      "Femme":"Brute",
      "Fiend":"-",
      "Foul":"Wild Bird",
      "Goddess":"Femme",
      "Godly Beast":"Divine",
      "Guardian":"Nation Ruler",
      "Haunt":"Earth Element",
      "Heavenly God":"Goddess",
      "Holy Beast":"Divine",
      "Nation Ruler":"Femme",
      "Nocturne":"Divine",
      "Raptor":"Evil Demon",
      "Reapers":"Earth Element",
      "Seraph":"Goddess",
      "Tyrant":"Nocturne",
      "Vile":"Earth Element",
      "Wild Bird":"Divine",
      "Wilder":"Evil Demon",
      "Yoma":"Aquans"
   }
}